### ISSUE TITLE
Upgrade to dotnet 8

### ISSUE THREAD

**Issue by razvangoga** [tye-v2/tye2#12]
- [x] upgrade all projects to dotnet 8 and C# 12 via the https://github.com/tye-v2/tye2/blob/main/Directory.Build.props file
- [x] update all nuget references that do not introduce breaking / code changes
- [x] clean up this hack from the initial fork : https://github.com/tye-v2/tye2/pull/8#discussion_r1494489936

**Comment by razvangoga** [comment]
@drakon660 do you want to take care of this one while i move forward with the packaging pipeline / push to nuget ?

**Comment by drakon660** [comment]
I can do that, two things

-  delete Microsoft namespace.
-  "clean up this hack from the initial fork" ? You mean this not working tests in the pipeline? I so how?

**Comment by razvangoga** [comment]
> * delete Microsoft namespace.

i'll do the renames as part of the push to nuget issues - i need to rename the projects there anyway to get the new exe names


> * "clean up this hack from the initial fork" ? You mean this not working tests in the pipeline? If so how?
I meant the part about the --roll-forward from here. I think with tye itself on 8, the roll forward will not be needed.
<img width="709" alt="image" src="https://github.com/tye-v2/tye2/assets/1067494/66e51517-b87d-48a2-b7b1-75d726057a6d">

**Comment by drakon660** [comment]
Ok, I got it. Will do

**Comment by razvangoga** [comment]
merged
