### ISSUE TITLE
Update the yaml schema definition and related docs

### ISSUE THREAD

**Issue by razvangoga** [tye-v2/tye2#24]
The tye.yaml has a schema definition file ([tye-schema.json](https://github.com/tye-v2/tye2/blob/main/src/schema/tye-schema.json)) found here: https://github.com/tye-v2/tye2/tree/main/src/schema.

The [README.md](https://github.com/tye-v2/tye2/blob/main/src/schema/README.md) describes how it can be used in VSCode to get schema validation.

------

The following should be fixed:

- [ ] update the readme (and any doc pages if any) with an url pointing to the file in the tye2 repo
     - [ ] https://github.com/tye-v2/tye2/blob/main/docs/reference/schema.md
- [ ] update the tye-schema.json to reflect what is currently possible to define in the tye.yaml
     - [ ] For example the routes enumeration is shown as an error, althow the tool accepts it's values <img width="426" alt="image" src="https://github.com/tye-v2/tye2/assets/1067494/8ae3e77e-6ea4-4b51-8b38-3893e90a5e61">

**Comment by drakon660** [comment]
Could you go with the PR?
