### ISSUE TITLE
Running Unit Tests

### ISSUE THREAD

**Issue by razvangoga** [tye-v2/tye2#6]
- [x] updated all sample projects used in unit tests to net 7 or 8
- [x] make all unit tests pass

**Comment by drakon660** [comment]
This is my tests results
![image](https://github.com/razvangoga/tye2/assets/3002778/1257fbf2-be74-42a6-b584-d36efab6378d)

**Comment by drakon660** [comment]
This is actually how it looks like in my environment:

![image](https://github.com/razvangoga/tye2/assets/3002778/964c1a30-61a0-4a6a-89ea-2a9613a3f33f)

**Comment by razvangoga** [comment]
Yes all is pushed - do you have docker running in the background? Some tests use tye configs that spin up containers.

In any case, you clone locally and use as a control the original tye repo

**Comment by drakon660** [comment]
I have docker, we need to add additional info to readme to have docker installed (add volume to appdata) and install azure function tools, tonight I will investigate it further.

**Comment by drakon660** [comment]
2 tests are still not working. Downloading solution and installing all missing parts (e.g docker) gives 19 failing e2e test at starting point. Tests definitely doesn't provide fast feedback especially those e2e and are difficult to maintain, there are a lot of places to improve.

**Comment by drakon660** [comment]
tests fixed, please check.

**Comment by drakon660** [comment]
I don't see any comments, dapr installed from https://docs.dapr.io/getting-started/install-dapr-cli/ + dapr init.

**Comment by razvangoga** [comment]
they are inline in the conversation tab of the PR 
<img width="1321" alt="image" src="https://github.com/tye-v2/tye2/assets/1067494/e3d985a3-1b7a-4a4c-bbde-e91e9fa898bf">

**Comment by drakon660** [comment]
I should finish a review
<img width="1374" alt="Screenshot 2024-02-19 at 14 45 11" src="https://github.com/tye-v2/tye2/assets/3002778/e1e91710-0b3e-46e8-8e60-7454d7df0298">

**Comment by razvangoga** [comment]
try now

**Comment by drakon660** [comment]
close the issue?

**Comment by razvangoga** [comment]
@drakon660 i've merged de PR. thank you for the effort!

I'm working as we speak on #7 to get a working action pipeline that runs the tests.
