### ISSUE TITLE
Github Actions Pipeline - run unit tests as PR validation and on demand

### ISSUE THREAD

**Issue by razvangoga** [tye-v2/tye2#7]
- [x] new github actions pipeline for continuous integration
 - [x] runs on demand
 - [x] runs as a mandatory check for all PRs

**Comment by razvangoga** [comment]
## general notes

 - moved all old MS CI / build stuff to **_.old-ms-ci_** folder
 - removed the [MS Arcade](https://github.com/dotnet/arcade) project build configuration in favour of vanilla **_dotnet_** commands (build / test)
 - CI build pipeline is in https://github.com/tye-v2/tye2/blob/feature/7-ci-pipeline/.github/workflows/ci.yaml

## on linux agent

 - almost all tests are green : **203 / 209**
<img width="266" alt="image" src="https://github.com/tye-v2/tye2/assets/1067494/a6b4b64d-32ce-4eec-843b-84b0a4de49a0">

- the red tests are due to **host.docker.internal** not being accesible in the linux variant of docker
  - https://github.com/docker/for-linux/issues/264
  - https://stackoverflow.com/a/43541732/45091
  - even aspire has a workaround for this : https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting/Utils/HostNameResolver.cs
- i've disabled the red tests for now (by adding a xUnit trait for them and filtering them out based on it): 
<img width="557" alt="image" src="https://github.com/tye-v2/tye2/assets/1067494/425ebed3-cfe0-47e9-bfbd-311c65a3f4f2">

## on windows agent

- the windows agents are only partially usable because they seem to use the **Windows Container** version of **Docker Desktop** => any linux only container image (ex Redis for Dapr) is not usable on it

## macos agents

- the run minute for a macos agent is [10x as expensive ](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#minute-multipliers)as a linux one 👎 
- does not come with Docker Desktop installed and the installation takes a lot  of time

**Comment by razvangoga** [comment]
When running as PR check the test results are published in the PR thread 
<img width="749" alt="image" src="https://github.com/tye-v2/tye2/assets/1067494/97ddf455-cd1b-4112-92fd-e3de236d8681">

**Comment by drakon660** [comment]
Great Job!

Regarding agents, what do you think would be future approach, because we need a pipeline to release Tye2 especially on Windows 
and also macOS?

**Comment by razvangoga** [comment]
for the release i think all agents should work - most of my problems with the windows and macos have to do with the docker instance on them (or lack thereof).

for pack and push we only need the source code and the dotnet sdk
